version: '3'
services:
  mongo: 
    container_name: mongo
    image: mongo 
    ports: 
      - "27017:27017"
  node-server:
    container_name: backend
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    ports: 
      - 5000:5000
    volumes: 
      - .:/app
      - /app/node_modules
